us:
  build: .
  dockerfile: dockerflix.us
  ports:
  - "80:80"
  - "443:443"
  restart: always
bind:
  build: bind
  dockerfile: Dockerfile
  ports:
    - "53:53/udp"
  net: host
  volumes:
    - ./bind/config:/data
  restart: always 
